# Generated by Django 4.2.7 on 2023-11-17 13:15

from django.db import migrations, models
import snippets.models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='id',
            field=models.CharField(default=snippets.models.short_uuid, max_length=6, primary_key=True, serialize=False, unique=True),
        ),
    ]
